# Generated by Django 5.2.15 on 2026-08-13 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0134_evolury_work_stage_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringWorkItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual')], max_length=20)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('monthly_mode', models.CharField(blank=True, choices=[('day_of_month', 'Dia do mês'), ('weekday_of_month', 'Dia da semana do mês')], max_length=20, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('week_of_month', models.SmallIntegerField(blank=True, null=True)),
                ('weekday_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month_of_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_of_day', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_mode', models.CharField(choices=[('never', 'Nunca'), ('on_date', 'Em uma data'), ('after_count', 'Após N ocorrências')], default='never', max_length=20)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_after_count', models.PositiveIntegerField(blank=True, null=True)),
                ('generation_mode', models.CharField(choices=[('schedule', 'Por agenda'), ('after_completion', 'Após a conclusão')], default='schedule', max_length=20)),
                ('days_after_completion', models.PositiveIntegerField(blank=True, null=True)),
                ('skip_while_previous_open', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('occurrences_created', models.PositiveIntegerField(default=0)),
                ('template_description_html', models.TextField(blank=True, default='<p></p>')),
                ('template_priority', models.CharField(default='none', max_length=30)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('template_assignees', models.ManyToManyField(blank=True, related_name='recurring_work_items_assigned', to=settings.AUTH_USER_MODEL)),
                ('template_estimate_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_work_items', to='db.estimatepoint')),
                ('template_labels', models.ManyToManyField(blank=True, related_name='recurring_work_items', to='db.label')),
                ('template_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_work_items', to='db.state')),
                ('template_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_work_items', to='db.issuetype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Recurring Work Item',
                'verbose_name_plural': 'Recurring Work Items',
                'db_table': 'recurring_work_items',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecurringWorkItemOccurrence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scheduled_for', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_occurrences', to='db.issue')),
                ('recurring_work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='db.recurringworkitem')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_occurrences', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Recurring Work Item Occurrence',
                'verbose_name_plural': 'Recurring Work Item Occurrences',
                'db_table': 'recurring_work_item_occurrences',
                'ordering': ('-scheduled_for',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('recurring_work_item', 'scheduled_for'), name='recurring_occurrence_unique_schedule_when_deleted_at_null')],
            },
        ),
    ]
