# Generated by Django 5.2.15 on 2026-08-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0135_evolury_recurring_work_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringworkitem',
            name='monthly_mode',
            field=models.CharField(blank=True, choices=[('day_of_month', 'Dia do mês'), ('last_day', 'Último dia do mês'), ('weekday_of_month', 'Dia da semana do mês')], max_length=20, null=True),
        ),
    ]
