# Copyright (c) 2026-present Evolury
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Evolury: vencimento relativo da subtarefa na recorrência (ADR 0010, F7).
# Tabela própria porque `issues` é a maior do banco e isto é recurso de nicho;
# a cascata dos dois lados faz a limpeza sozinha.

# Generated by Django 5.2.15 on 2026-08-14 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0138_evolury_antecedencia_em_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSubtaskSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('anchor', models.CharField(choices=[('after_creation', 'Após o nascimento da ocorrência'), ('before_due', 'Antes do vencimento da ocorrência')], max_length=20)),
                ('offset_days', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('recurring_work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_schedules', to='db.recurringworkitem')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_subtask_schedules', to='db.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Recurring Subtask Schedule',
                'verbose_name_plural': 'Recurring Subtask Schedules',
                'db_table': 'recurring_subtask_schedules',
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('recurring_work_item', 'subtask'), name='recurring_subtask_schedule_unique_when_deleted_at_null')],
            },
        ),
    ]
