# Copyright (c) 2026-present Evolury
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Evolury: pular uma ocorrência sem mexer na série (ADR 0010, F9).
# Coluna só, sem tabela nova: pular é gravar a linha de ocorrência antes da
# hora, e a unicidade (regra, data prevista) que já garante idempotência passa
# a garantir que aquela data não gera.

# Generated by Django 5.2.15 on 2026-08-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0139_evolury_vencimento_relativo_subtarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringworkitemoccurrence',
            name='skipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Skipped At'),
        ),
    ]
