# Copyright (c) 2026-present Evolury
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Evolury: propriedades personalizadas da tarefa (ADR 0011, P1).
# Três tabelas na forma que Estimate + EstimatePoint já usa: configuração por
# projeto, opções, e valor por tarefa em colunas tipadas. Nada as usa ainda —
# a P1 entrega o motor inerte de propósito.

# Generated by Django 5.2.15 on 2026-08-15 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0140_evolury_pular_ocorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueProperty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('select', 'Seleção única'), ('multi_select', 'Seleção múltipla'), ('currency', 'Moeda')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_card', models.BooleanField(default=False)),
                ('sort_order', models.FloatField(default=65535)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property',
                'verbose_name_plural': 'Issue Properties',
                'db_table': 'issue_properties',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='IssuePropertyOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='db.issueproperty')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property Option',
                'verbose_name_plural': 'Issue Property Options',
                'db_table': 'issue_property_options',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='IssuePropertyValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='db.issue')),
                ('issue_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='db.issueproperty')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('value_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='db.issuepropertyoption')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property Value',
                'verbose_name_plural': 'Issue Property Values',
                'db_table': 'issue_property_values',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='issueproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'name'), name='issue_property_unique_name_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='issuepropertyoption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue_property', 'name'), name='issue_property_option_unique_name_when_deleted_at_null'),
        ),
        migrations.AddIndex(
            model_name='issuepropertyvalue',
            index=models.Index(fields=['issue', 'issue_property'], name='issue_property_value_lookup'),
        ),
        migrations.AddConstraint(
            model_name='issuepropertyvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'issue_property', 'value_option'), name='issue_property_value_unique_option_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='issuepropertyvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('value_option__isnull', True)), fields=('issue', 'issue_property'), name='issue_property_value_unique_scalar_when_deleted_at_null'),
        ),
    ]
