# Generated by Django 5.2.16 on 2026-08-18 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0144_evolury_automacao_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStageSweep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ran_on', models.DateField()),
            ],
            options={
                'verbose_name': 'Work Stage Sweep',
                'verbose_name_plural': 'Work Stage Sweeps',
                'db_table': 'work_stage_sweeps',
                'ordering': ('-ran_on',),
            },
        ),
        migrations.AddField(
            model_name='workstage',
            name='automation_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workstage',
            name='is_due_later',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workstage',
            name='is_due_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workstage',
            name='is_due_tomorrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workstage',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='workstage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_due_today', True)), fields=('workspace', 'owner'), name='work_stage_single_due_today_per_owner_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='workstage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_due_tomorrow', True)), fields=('workspace', 'owner'), name='work_stage_single_due_tomorrow_per_owner_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='workstage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_due_later', True)), fields=('workspace', 'owner'), name='work_stage_single_due_later_per_owner_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='workstage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_overdue', True)), fields=('workspace', 'owner'), name='work_stage_single_overdue_per_owner_when_deleted_at_null'),
        ),
        migrations.AddField(
            model_name='workstagesweep',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workstagesweep',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_stage_sweeps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workstagesweep',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workstagesweep',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_stage_sweeps', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='workstagesweep',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'owner'), name='work_stage_sweep_unique_per_owner_when_deleted_at_null'),
        ),
    ]
